FROM gitlab/gitlab-ce:latest

MAINTAINER Gregory Buchenberger <gregory.buchenberger@charter.com>

VOLUME ["/etc/gitlab","/var/log/gitlab","/var/opt/gitlab"]

RUN chmod 2770 /var/opt/gitlab/git-data/repositories
